name: test
on:
  - push
  - pull_request
jobs:
  test:
    uses: japa/.github/.github/workflows/test.yml@main
  lint:
    uses: japa/.github/.github/workflows/lint.yml@main
  typecheck:
    uses: japa/.github/.github/workflows/typecheck.yml@main
